name: Manual workflow to build base Ubuntu 20.04 AMI with Packer

on:
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix does not work for hcl - skipping
      # fix backwards incompatibilities in template
      #- name: Fix Template
      #  uses: hashicorp/packer-github-actions@master
      #  with:
      #    command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=cleanup"
          target: packer.pkr.hcl
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_AMI_ACCOUNTS: ${{ secrets.AWS_AMI_ACCOUNTS }}
          AWS_OWNER: ${{ secrets.AWS_OWNER }}
